[build-system]
requires = ["scikit-build-core>=0.11", "pybind11>=3.0"]
build-backend = "scikit_build_core.build"

[project]
name = "orienteering_solver"
version = "0.0.1"
description = "Algorithms for the orienteering problem (C++ pybind extension)."
readme = "README.md"
authors = [ { name = "Ewan Clarke", email = "ewan.o.clarke@gmail.com" } ]
requires-python = ">=3.9"
license = "MIT"
